version: '3'
services:
    redis:
        image: redis:latest
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 5s
            timeout: 30s
            retries: 5
        restart: always

    rabbitmq:
        image: rabbitmq:latest
        healthcheck:
            test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
            interval: 5s
            timeout: 30s
            retries: 5
        ports:
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=pwd

    worker:
        build:
            context: ./worker
            dockerfile: worker.Dockerfile
        env_file:
            - "env/values-dev.env"
        depends_on:
            - redis
            - rabbitmq

    app:
        build:
            context: ./app
            dockerfile: app.Dockerfile
        ports:
            - "8080:8080"
        env_file:
            - "env/values-dev.env"
        depends_on:
            - redis
            - rabbitmq
